{{ config({ "materialized":'view',
 "alias":'DATE_DIM_VIEW',
 "schema": 'GOLD'
})}}
 
WITH view AS(
SELECT
    DATE_ID::INT AS DATE_ID
    ,STORE_DATE::DATE AS STORE_DATE
    ,ISHOLIDAY::VARCHAR(255) AS ISHOLIDAY
    ,INSERT_DTS::TIMESTAMP_NTZ(6) AS INSERT_DTS
    ,UPDATE_DTS::TIMESTAMP_NTZ(6) AS UPDATE_DTS
FROM {{ref('fact_snapshot')}}
)

SELECT *
FROM view v
GROUP BY
    DATE_ID, STORE_DATE, ISHOLIDAY, INSERT_DTS, UPDATE_DTS
ORDER BY
    DATE_ID