{{ config({ "materialized":'view',
 "alias":'FACT_VIEW',
 "schema": 'GOLD'
})}}
 
WITH view AS(
SELECT
    STORE AS STORE_ID
    ,DATE
    ,FUEL_PRICE
    ,TEMPERATURE AS STORE_TEMPERATURE
    ,UNEMPLOYMENT
    ,CPI
    ,MARKDOWN1
    ,MARKDOWN2
    ,MARKDOWN3
    ,MARKDOWN4
    ,MARKDOWN5
    ,INSERT_DTS
    ,UPDATE_DTS
    ,DBT_VALID_FROM AS VRSN_STRT_DTS
    ,COALESCE(DBT_VALID_TO , '9999-12-31 00:00:00.000') AS VRSN_END_DTS
FROM {{ref('fact_snapshot')}}
)

SELECT
    v.STORE_ID::INT AS STORE_ID
    ,d.DEPT::INT AS DEPT_ID
    ,v.DATE::DATE AS STORE_DATE
    ,d.WEEKLY_SALES::DECIMAL(20,2) AS STORE_WEEKLY_SALES
    ,v.FUEL_PRICE::DECIMAL(20,2) AS FUEL_PRICE
    ,v.STORE_TEMPERATURE::DECIMAL(20,2) AS STORE_TEMPERATURE
    ,v.UNEMPLOYMENT::DECIMAL(20,2) AS UNEMPLOYMENT
    ,v.CPI::DECIMAL(20,2) AS CPI
    ,v.MARKDOWN1::DECIMAL(20,2) AS MARKDOWN1
    ,v.MARKDOWN2::DECIMAL(20,2) AS MARKDOWN2
    ,v.MARKDOWN3::DECIMAL(20,2) AS MARKDOWN3
    ,v.MARKDOWN4::DECIMAL(20,2) AS MARKDOWN4
    ,v.MARKDOWN5::DECIMAL(20,2) AS MARKDOWN5
    ,v.INSERT_DTS::TIMESTAMP_NTZ(6) AS INSERT_DTS
    ,v.UPDATE_DTS::TIMESTAMP_NTZ(6) AS UPDATE_DTS
    ,v.VRSN_STRT_DTS::TIMESTAMP_NTZ(6) AS VRSN_STRT_DTS
    ,v.VRSN_END_DTS::TIMESTAMP_NTZ(6) AS VRSN_END_DTS
FROM view v
JOIN {{ref('transform_departments_load')}} d
    ON v.STORE_ID = d.STORE
    AND v.DATE = d.DATE
ORDER BY
    STORE_ID, DEPT_ID, STORE_DATE