{{ config({ "materialized":'view',
 "alias":'FACT_VIEW',
 "schema": 'GOLD'
})}}
 
WITH view AS(
SELECT
    STORE_ID
    ,DEPT_ID
    ,DATE_ID
    ,STORE_WEEKLY_SALES
    ,FUEL_PRICE
    ,STORE_TEMPERATURE
    ,UNEMPLOYMENT
    ,CPI
    ,MARKDOWN1
    ,MARKDOWN2
    ,MARKDOWN3
    ,MARKDOWN4
    ,MARKDOWN5
    ,INSERT_DTS
    ,UPDATE_DTS
    ,DBT_VALID_FROM::TIMESTAMP_NTZ(6) AS VRSN_STRT_DTS
    ,CAST(COALESCE(DBT_VALID_TO , '9999-12-31 00:00:00.000') AS TIMESTAMP_NTZ(6)) AS VRSN_END_DTS
FROM {{ref('fact_snapshot')}}
)

SELECT *
FROM view
ORDER BY
    STORE_ID, DEPT_ID, STORE_DATE