{{ config({ "materialized":'incremental',
"incremental_strategy":'merge',
 "unique_key":['STORE_ID','STORE_DATE'],
 "transient":true,
 "alias":'FACT_TRANSFORM',
 "pre_hook": macros_copy_fact_csv('FACT_COPY'),
 "schema": 'SILVER'
})}}

WITH transform AS(
SELECT 
    STORE AS STORE_ID
    ,DATE AS STORE_DATE
    ,TEMPERATURE AS STORE_TEMPERATURE
    ,FUEL_PRICE AS FUEL_PRICE
    ,MARKDOWN1 AS MARKDOWN1
    ,MARKDOWN2 AS MARKDOWN2
    ,MARKDOWN3 AS MARKDOWN3
    ,MARKDOWN4 AS MARKDOWN4
    ,MARKDOWN5 AS MARKDOWN5 
    ,CPI AS CPI
    ,UNEMPLOYMENT AS UNEMPLOYMENT
    ,ISHOLIDAY AS ISHOLIDAY
    ,INSERT_DTS AS INSERT_DTS
    ,UPDATE_DTS AS UPDATE_DTS
FROM {{source('source','FACT_COPY')}}

{% if is_incremental() %}
    where UPDATE_DTS > (select max(UPDATE_DTS) from {{this}})
    {% endif %}
)

SELECT
    t.STORE_ID::INT AS STORE_ID
    ,d.DEPT::INT AS DEPT_ID
    ,t.STORE_DATE::DATE AS STORE_DATE
    ,d.WEEKLY_SALES::DECIMAL(20,2) AS STORE_WEEKLY_SALES
    ,t.FUEL_PRICE::DECIMAL(20,2) AS FUEL_PRICE
    ,t.STORE_TEMPERATURE::DECIMAL(20,2) AS STORE_TEMPERATURE
    ,t.UNEMPLOYMENT::DECIMAL(20,2) AS UNEMPLOYMENT
    ,t.CPI::DECIMAL(20,2) AS CPI
    ,t.MARKDOWN1::DECIMAL(20,2) AS MARKDOWN1
    ,t.MARKDOWN2::DECIMAL(20,2) AS MARKDOWN2
    ,t.MARKDOWN3::DECIMAL(20,2) AS MARKDOWN3
    ,t.MARKDOWN4::DECIMAL(20,2) AS MARKDOWN4
    ,t.MARKDOWN5::DECIMAL(20,2) AS MARKDOWN5
    ,t.ISHOLIDAY::VARCHAR(255) AS ISHOLIDAY
    ,t.INSERT_DTS::TIMESTAMP_NTZ(6) AS INSERT_DTS
    ,t.UPDATE_DTS::TIMESTAMP_NTZ(6) AS UPDATE_DTS
FROM transform t
JOIN {{source('source','DEPARTMENTS_COPY')}} d
    ON t.STORE_ID = d.STORE
    AND t.STORE_DATE = d.DATE
ORDER BY
    1, 2, 3